apiVersion: v1
kind: Service
metadata:
  name: sg-events-service
spec:
  type: NodePort
  selector:
    app: sg-events-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
